//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSBom
    {
        public string ProInvenCode { get; set; }
        public string MatInvenCode { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual BSInven BSInven { get; set; }
        public virtual BSInven BSInven1 { get; set; }
    }
}
