//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BSCustomer()
        {
            this.CUAfterServices = new HashSet<CUAfterService>();
            this.CURelRecords = new HashSet<CURelRecord>();
            this.CUSellChances = new HashSet<CUSellChance>();
            this.SEGathers = new HashSet<SEGather>();
            this.SEOrders = new HashSet<SEOrder>();
            this.SEOutStores = new HashSet<SEOutStore>();
        }
    
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string EmployeeCode { get; set; }
        public string AtrMan { get; set; }
        public string TelephoneCode { get; set; }
        public string FaxCode { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string Linkman { get; set; }
        public string Url { get; set; }
        public string Address { get; set; }
        public string GradeCode { get; set; }
        public string StateCode { get; set; }
        public string CreditCode { get; set; }
        public string TradeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUAfterService> CUAfterServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CURelRecord> CURelRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSellChance> CUSellChances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGather> SEGathers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEOrder> SEOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEOutStore> SEOutStores { get; set; }
    }
}
