//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSInven
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BSInven()
        {
            this.BSBoms = new HashSet<BSBom>();
            this.BSBoms1 = new HashSet<BSBom>();
            this.CUSellChances = new HashSet<CUSellChance>();
            this.PRInStores = new HashSet<PRInStore>();
            this.PRPlans = new HashSet<PRPlan>();
            this.PRProduces = new HashSet<PRProduce>();
            this.PRProduceItems = new HashSet<PRProduceItem>();
            this.PUInStores = new HashSet<PUInStore>();
            this.PUOrders = new HashSet<PUOrder>();
            this.SEOrders = new HashSet<SEOrder>();
            this.SEOutStores = new HashSet<SEOutStore>();
            this.STChecks = new HashSet<STCheck>();
            this.STGetMaterials = new HashSet<STGetMaterial>();
            this.STStocks = new HashSet<STStock>();
            this.STLosses = new HashSet<STLoss>();
        }
    
        public string InvenCode { get; set; }
        public string InvenName { get; set; }
        public string InvenTypeCode { get; set; }
        public string SpecsModel { get; set; }
        public string MeaUnit { get; set; }
        public Nullable<decimal> SelPrice { get; set; }
        public Nullable<decimal> PurPrice { get; set; }
        public Nullable<int> SmallStockNum { get; set; }
        public Nullable<int> BigStockNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSBom> BSBoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSBom> BSBoms1 { get; set; }
        public virtual BSInvenType BSInvenType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSellChance> CUSellChances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRInStore> PRInStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRPlan> PRPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRProduce> PRProduces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRProduceItem> PRProduceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUInStore> PUInStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUOrder> PUOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEOrder> SEOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEOutStore> SEOutStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STCheck> STChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STGetMaterial> STGetMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STStock> STStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STLoss> STLosses { get; set; }
    }
}
