//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSellChance
    {
        public int SellId { get; set; }
        public string CustomerCode { get; set; }
        public string Theme { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string ChanceCode { get; set; }
        public Nullable<System.DateTime> ForeDate { get; set; }
        public string InvenCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> CUMoney { get; set; }
        public string Remark { get; set; }
    
        public virtual BSCustomer BSCustomer { get; set; }
        public virtual BSInven BSInven { get; set; }
        public virtual CUChance CUChance { get; set; }
    }
}
