//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIPurCost
    {
        public string FIPurCode { get; set; }
        public Nullable<System.DateTime> FIPurDate { get; set; }
        public string OperatorCode { get; set; }
        public string SupplierCode { get; set; }
        public string AccountCode { get; set; }
        public string EmployeeCode { get; set; }
        public string CostCode { get; set; }
        public Nullable<decimal> FIMoney { get; set; }
        public string Remark { get; set; }
        public string IsFlag { get; set; }
    
        public virtual BSAccount BSAccount { get; set; }
        public virtual BSCost BSCost { get; set; }
        public virtual BSEmployee BSEmployee { get; set; }
        public virtual SYOperator SYOperator { get; set; }
    }
}
