//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProduce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRProduce()
        {
            this.PRInStores = new HashSet<PRInStore>();
            this.PRProduceItems = new HashSet<PRProduceItem>();
            this.STGetMaterials = new HashSet<STGetMaterial>();
        }
    
        public string PRProduceCode { get; set; }
        public Nullable<System.DateTime> PRProduceDate { get; set; }
        public string OperatorCode { get; set; }
        public string PRPlanCode { get; set; }
        public string DepartmentCode { get; set; }
        public string InvenCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string IsFlag { get; set; }
        public string IsComplete { get; set; }
    
        public virtual BSDepartment BSDepartment { get; set; }
        public virtual BSInven BSInven { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRInStore> PRInStores { get; set; }
        public virtual PRPlan PRPlan { get; set; }
        public virtual SYOperator SYOperator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRProduceItem> PRProduceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STGetMaterial> STGetMaterials { get; set; }
    }
}
