//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProduceItem
    {
        public int Id { get; set; }
        public string PRProduceCode { get; set; }
        public string InvenCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> GetQuantity { get; set; }
        public Nullable<int> UseQuantity { get; set; }
    
        public virtual BSInven BSInven { get; set; }
        public virtual PRProduce PRProduce { get; set; }
    }
}
