//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUInStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUInStore()
        {
            this.PUPays = new HashSet<PUPay>();
        }
    
        public string PUInCode { get; set; }
        public Nullable<System.DateTime> PUInDate { get; set; }
        public string OperatorCode { get; set; }
        public string SupplierCode { get; set; }
        public string StoreCode { get; set; }
        public string InvenCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PUMoney { get; set; }
        public string PUOrderCode { get; set; }
        public string EmployeeCode { get; set; }
        public string IsFlag { get; set; }
    
        public virtual BSInven BSInven { get; set; }
        public virtual BSStore BSStore { get; set; }
        public virtual BSSupplier BSSupplier { get; set; }
        public virtual SYOperator SYOperator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUPay> PUPays { get; set; }
    }
}
