//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUPay
    {
        public string PUPayCode { get; set; }
        public Nullable<System.DateTime> PUPayDate { get; set; }
        public string OperatorCode { get; set; }
        public string PUInCode { get; set; }
        public Nullable<System.DateTime> PUInDate { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<decimal> PUMoney { get; set; }
        public string AccountCode { get; set; }
        public string EmployeeCode { get; set; }
        public string Remark { get; set; }
        public string IsFlag { get; set; }
    
        public virtual BSAccount BSAccount { get; set; }
        public virtual BSSupplier BSSupplier { get; set; }
        public virtual PUInStore PUInStore { get; set; }
        public virtual SYOperator SYOperator { get; set; }
    }
}
