//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGather
    {
        public string SEGatherCode { get; set; }
        public Nullable<System.DateTime> SEGatherDate { get; set; }
        public string OperatorCode { get; set; }
        public string SEOutCode { get; set; }
        public Nullable<System.DateTime> SEOutDate { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<decimal> SEMoney { get; set; }
        public string AccountCode { get; set; }
        public string EmployeeCode { get; set; }
        public string Remark { get; set; }
        public string IsFlag { get; set; }
    
        public virtual BSAccount BSAccount { get; set; }
        public virtual BSCustomer BSCustomer { get; set; }
        public virtual SEOutStore SEOutStore { get; set; }
        public virtual SYOperator SYOperator { get; set; }
    }
}
