//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYAssignRight
    {
        public string OperatorCode { get; set; }
        public string ModuleTag { get; set; }
        public string RightTag { get; set; }
        public string IsRight { get; set; }
    
        public virtual INModule INModule { get; set; }
        public virtual INRight INRight { get; set; }
    }
}
